name: Train in dev and prod environments

on:
  push:
    branches:
      - 'main'

jobs:
  train-dev:
    runs-on: ubuntu-latest
    environment:
        name: development 
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job in dev environment
      run: |
        az ml job create --file src/job-dev.yml --workspace-name mlwork --resource-group mlops --stream

  train-prod:
    runs-on: ubuntu-latest
    needs: train-dev
    environment:
      name: "production"
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job in prod environment
      run: |
        az ml job create --file src/job-prod.yml --workspace-name mlwork --resource-group mlops --stream